### ISSUE TITLE
findAndConnect returns FALSE in android 10

### ISSUE THREAD

**Issue by krishnaaro** [alternadom/WiFiFlutter#85] opened 2020-10-28 04:54 UTC
after android Q update, can't able to connect through findAndConnect function. no error log occurred too. please let me know if I'm missing something .... !

**Comment by daadu** [comment] 2020-10-29 11:51
Fix for this issue is being work on at #88.

Recommend you to test/review it and provide feedback (instruction are in the PR itself). Merging of #88 will close this issue as well.

**Comment by krishnaaro** [comment] 2020-10-31 05:26
findAndConnect('SSID', 'PASSWORD') returns TRUE, but there's no sign that my device connected to that SSID. got log as below.

```
D/Wifi ID (28295): motorola one power 3260   "motorola one power 3260"
W/ConnectivityManager.CallbackHandler(28295): callback not found for CALLBACK_CAP_CHANGED message
```

**Comment by daadu** [comment] 2020-10-31 05:53
@krishnaaro This is known, I am working on it.

**Comment by krishnaaro** [comment] 2020-11-02 12:47
> @krishnaaro This is known, I am working on it.

@daadu  any update .... !?

**Comment by daadu** [comment] 2020-11-03 06:00
@krishnaaro try now, run `flutter pub upgrade`.

Also test `disconnect` method.

**Comment by daadu** [comment] 2020-11-03 06:00
Please also verify that the older versions work too.

**Comment by daadu** [comment] 2020-11-10 13:15
@krishnaaro Did you test it?

**Comment by krishnaaro** [comment] 2020-11-11 16:10
Bingo, only if GPS and WIFI turned ON manually in Android 10.

**Comment by daadu** [comment] 2020-11-12 07:02
new issue #90 regarding location services required.

**Comment by krishnaaro** [comment] 2020-11-12 11:42
> Please also verify that the older versions (<29) work too.

Yeah it's happening smooth ....

**Comment by krishnaaro** [comment] 2020-11-12 11:49
> Bingo, only if GPS and WIFI turned ON manually in Android 10.
> 
> Edit->
> 
> my_objective: mobile has to connect with an IOT device, then to take Mac ID through localhost. in this case I'm getting like below
> `Connection failed (OS Error: Network is unreachable, errno = 101), address = 192.87.3.28, port = 80`
> 
> I'm facing issue like, can't access the local host though wifi network connected though this app .... in anddroid Q.
> similar to below.
> 
> > findAndConnect('SSID', 'PASSWORD') returns TRUE, but there's no sign that my device connected to that SSID. got log as below.
> > ```
> > D/Wifi ID (28295): motorola one power 3260   "motorola one power 3260"
> > W/ConnectivityManager.CallbackHandler(28295): callback not found for CALLBACK_CAP_CHANGED message
> > ```

Note: if I connect WIFI manually, i can access localhost and get my mac id details in chrome browser ....

**Comment by krishnaaro** [comment] 2020-11-13 14:24
any update @daadu ....!

**Comment by daadu** [comment] 2020-11-13 14:34
I am not getting what you are asking?

**Comment by krishnaaro** [comment] 2020-11-13 14:49
> I am not getting what you are asking?

please try connect an android 10 device to an SSID, then check you have internet access or not .... !?

**Comment by JavaDeveloper08** [comment] 2020-11-20 11:16
Hi, @krishnaaro 
I am getting same error, I am connectin to an SSD via an adroid 10, but it has no internet access.

@daadu , do you have any suggestion to solve for this ?

**Comment by daadu** [comment] 2020-11-21 04:34
I will try and fix this, as of now try using `forceWifiUsage` after connecting.

**Closed** 2020-11-25 06:46 UTC

**Comment by JavaDeveloper08** [comment] 2020-11-25 07:25
Hi, @daadu 

did you solve the problem, I tried it with last version, result is same.

**Comment by daadu** [comment] 2020-11-25 12:57
@JavaDeveloper08 no, I haven't worked on it yet.

**Comment by JavaDeveloper08** [comment] 2020-11-25 12:58
@daadu,

thanks for your reply,

I am looking forward  to hear :)

**Comment by daadu** [comment] 2020-11-25 17:36
@krishnaaro @JavaDeveloper08 `forceWifiUsage` should enforce the the request is made through Wifi. Have you tried it? Does that work for you?

**Comment by krishnaaro** [comment] 2020-11-26 06:06
> @krishnaaro @JavaDeveloper08 `forceWifiUsage` should enforce the the request is made through Wifi. Have you tried it? Does that work for you?

No luck ....

**Comment by JavaDeveloper08** [comment] 2020-11-26 07:00
@daadu , I tried it but result is same, no internet access.
Generally, we have no problem to connect Wifi. The problem is no internet access after connecting to wifi on Android 10 devices.

**Comment by daadu** [comment] 2020-11-26 17:14
@JavaDeveloper08 @krishnaaro Raised new issue regarding it, further discussion will be continued there.
