### ISSUE TITLE
Fails to build for iOS..

### ISSUE THREAD

**Issue by tristan2468** [alternadom/WiFiFlutter#7] opened 2018-06-27 10:22 UTC
Launching lib/main.dart on iPhone X in debug mode...
Running pod install...
Starting Xcode build...
Xcode build done.
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
Xcode's output:
↳
    === BUILD TARGET qr_mobile_vision OF PROJECT Pods WITH CONFIGURATION Debug ===
    Undefined symbols for architecture x86_64:
      "_OBJC_CLASS_$_NEHotspotConfigurationManager", referenced from:
          objc-class-ref in SwiftWifiIotPlugin.o
      "_OBJC_CLASS_$_NEHotspotConfiguration", referenced from:
          objc-class-ref in SwiftWifiIotPlugin.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
Could not build the application for the simulator.
Error launching application on iPhone X.

**Comment by alternadom** [comment] 2018-06-27 11:16
Hi, 
I'm on vacation but first idea, you can't use this lib in simulator...
When I come back, I will test that!

**Comment by tristan2468** [comment] 2018-06-27 12:20
OK. This was in the Simulator.
Thanks.

**Comment by alternadom** [comment] 2018-07-03 14:29
Hi,
So the problem is not anymore ? 
Can we close the issue ?

**Comment by tristan2468** [comment] 2018-07-03 14:42
In a similar plugin I have written for my own use, I have wrapped all code which will not run in the Simulator with 
```
#if !arch(i386) && !arch(x86_64)
...
#endif
```

e.g.
```
#if !arch(i386) && !arch(x86_64)
import NetworkExtension
#endif
```

**Comment by alternadom** [comment] 2018-07-03 14:46
Ok, but this is just for iOS, right ?

**Comment by tristan2468** [comment] 2018-07-03 14:50
Yes, inside the Swift file.

**Comment by minhvn** [comment] 2018-10-25 17:35
> Hi,
> I'm on vacation but first idea, you can't use this lib in simulator...
> When I come back, I will test that!

Same error :)

**Closed** 2020-06-17 06:55 UTC
Labels: enhancement
